import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

/**
 * GitHub deployment via Personal Access Token.
 *
 * v1: PAT only. OAuth listed in the spec as a follow-up. Uses the Git Data
 * API to push a tree of files into either a freshly created repo or an
 * existing one. Each deploy creates a single commit on the default branch.
 *
 * Token must include `repo` scope (or `public_repo` for public-only).
 */

const fileSchema = z.object({ path: z.string().min(1), content: z.string() });

const inputSchema = z.object({
  token: z.string().min(1),
  mode: z.enum(["create", "existing"]),
  /** "create" mode: just the new repo name. "existing": "owner/repo". */
  repo: z.string().min(1),
  /** Optional description used when creating a new repo. */
  description: z.string().optional(),
  files: z.array(fileSchema).min(1),
  commitMessage: z.string().min(1),
  isPrivate: z.boolean().default(false),
});

class GhError extends Error {
  constructor(public code: "bad_token" | "repo_exists" | "permission_denied" | "not_found" | "network" | "unknown", message: string) {
    super(message);
  }
}

const GH = "https://api.github.com";

function headers(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "HYCS-Deploy",
    "Content-Type": "application/json",
  };
}

async function gh(token: string, path: string, init?: { method?: string; body?: unknown }): Promise<unknown> {
  const r = await fetch(`${GH}${path}`, {
    method: init?.method || "GET",
    headers: headers(token),
    body: init?.body !== undefined ? JSON.stringify(init.body) : undefined,
  });
  const text = await r.text();
  let body: unknown = null;
  try { body = text ? JSON.parse(text) : null; } catch { body = text; }
  if (!r.ok) {
    if (r.status === 401) throw new GhError("bad_token", "GitHub authentication could not be completed. Please reconnect your account and try again.");
    if (r.status === 403) throw new GhError("permission_denied", "HYCS does not have permission to access this repository.");
    if (r.status === 404) throw new GhError("not_found", "Repository not found. Check the name and try again.");
    if (r.status === 422 && /name already exists/i.test(JSON.stringify(body))) {
      throw new GhError("repo_exists", "A repository with this name already exists. Choose another name or use the existing repository option.");
    }
    throw new GhError("unknown", `GitHub error (${r.status}): ${typeof body === "string" ? body : JSON.stringify(body)}`);
  }
  return body;
}

function b64(s: string): string {
  // Buffer is available in the Worker runtime via nodejs_compat.
  return Buffer.from(s, "utf8").toString("base64");
}

export const deployToGithub = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => inputSchema.parse(d))
  .handler(async ({ data }) => {
    try {
      const me = (await gh(data.token, "/user")) as { login: string };
      let owner = me.login;
      let repoName = data.repo;

      if (data.mode === "create") {
        const created = (await gh(data.token, "/user/repos", {
          method: "POST",
          body: {
            name: data.repo,
            description: data.description || "Generated by HYCS",
            private: data.isPrivate,
            auto_init: true,
          },
        })) as { name: string; owner: { login: string }; default_branch: string };
        owner = created.owner.login;
        repoName = created.name;
      } else {
        // "owner/repo" or bare "repo" (use me.login)
        if (data.repo.includes("/")) {
          const [o, r] = data.repo.split("/");
          owner = o;
          repoName = r;
        }
        await gh(data.token, `/repos/${owner}/${repoName}`);
      }

      const repoInfo = (await gh(data.token, `/repos/${owner}/${repoName}`)) as { default_branch: string };
      const branch = repoInfo.default_branch || "main";

      // Get head sha + base tree
      const ref = (await gh(data.token, `/repos/${owner}/${repoName}/git/ref/heads/${branch}`)) as { object: { sha: string } };
      const headSha = ref.object.sha;
      const headCommit = (await gh(data.token, `/repos/${owner}/${repoName}/git/commits/${headSha}`)) as { tree: { sha: string } };
      const baseTreeSha = headCommit.tree.sha;

      // Create blobs
      const blobs: { path: string; sha: string }[] = [];
      for (const f of data.files) {
        const b = (await gh(data.token, `/repos/${owner}/${repoName}/git/blobs`, {
          method: "POST",
          body: { content: b64(f.content), encoding: "base64" },
        })) as { sha: string };
        blobs.push({ path: f.path, sha: b.sha });
      }

      // Build tree
      const tree = (await gh(data.token, `/repos/${owner}/${repoName}/git/trees`, {
        method: "POST",
        body: {
          base_tree: baseTreeSha,
          tree: blobs.map((b) => ({ path: b.path, mode: "100644", type: "blob", sha: b.sha })),
        },
      })) as { sha: string };

      // Commit
      const commit = (await gh(data.token, `/repos/${owner}/${repoName}/git/commits`, {
        method: "POST",
        body: { message: data.commitMessage, tree: tree.sha, parents: [headSha] },
      })) as { sha: string };

      // Update ref
      await gh(data.token, `/repos/${owner}/${repoName}/git/refs/heads/${branch}`, {
        method: "PATCH",
        body: { sha: commit.sha, force: false },
      });

      return {
        ok: true as const,
        repoUrl: `https://github.com/${owner}/${repoName}`,
        commitSha: commit.sha,
        branch,
        owner,
        repo: repoName,
        pagesHint: `https://${owner}.github.io/${repoName}/`,
      };
    } catch (e) {
      if (e instanceof GhError) return { ok: false as const, code: e.code, message: e.message };
      return { ok: false as const, code: "unknown" as const, message: e instanceof Error ? e.message : "Deployment failed." };
    }
  });
