import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Link } from "@tanstack/react-router";
import { ExternalLink, Github, Loader2, X, Check, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import JSZip from "jszip";
import { deployToGithub } from "@/lib/github-deploy.functions";
import { useSettings } from "@/lib/likeable-settings";
import { wrapPage, type Project } from "@/lib/likeable-store";

type Props = {
  open: boolean;
  onClose: () => void;
  project: Project;
};

function buildFiles(project: Project): { path: string; content: string }[] {
  const out: { path: string; content: string }[] = [];
  for (const [slug, page] of Object.entries(project.pages)) {
    const path = slug === "home" ? "index.html" : `${slug}.html`;
    out.push({ path, content: wrapPage(project, slug) });
  }
  out.push({ path: "shared/header.html", content: project.shared.headerHtml || "" });
  out.push({ path: "shared/footer.html", content: project.shared.footerHtml || "" });
  out.push({ path: "shared/theme.css", content: project.shared.themeCss || "" });
  const readme = [
    `# ${project.brand || "HYCS project"}`,
    "",
    project.initialTitle ? `> ${project.initialTitle}` : "",
    "",
    `Generated by [HYCS](https://github.com/dev-kuzivakwashe/hycs) on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "## Pages",
    ...Object.entries(project.pages).map(([s, p]) => `- ${s === "home" ? "index.html" : `${s}.html`} - ${p.title}`),
    "",
    "## Local preview",
    "",
    "Open `index.html` directly in a browser, or run any static file server in this folder.",
    "",
    "## Deploy",
    "",
    "Drop this folder into GitHub Pages, Cloudflare Pages, Netlify, Vercel, or any static host. No build step required.",
    "",
  ].filter(Boolean).join("\n");
  out.push({ path: "README.md", content: readme });
  return out;
}

export function GithubDeployModal({ open, onClose, project }: Props) {
  const { settings, update } = useSettings();
  const deploy = useServerFn(deployToGithub);
  const [mode, setMode] = useState<"create" | "existing">("create");
  const [repoName, setRepoName] = useState((project.brand || "hycs-site").toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-|-$/g, ""));
  const [commitMessage, setCommitMessage] = useState("Initial project generation");
  const [isPrivate, setIsPrivate] = useState(false);
  const [tokenDraft, setTokenDraft] = useState(settings.githubToken);
  const [status, setStatus] = useState<"idle" | "deploying" | "success" | "failed">("idle");
  const [result, setResult] = useState<{ repoUrl: string; pagesHint?: string; commitSha?: string } | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!open) return null;
  const hasToken = !!settings.githubToken;

  async function downloadZip() {
    const files = buildFiles(project);
    const zip = new JSZip();
    files.forEach((f) => zip.file(f.path, f.content));
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${repoName || "hycs-site"}.zip`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function run() {
    if (!settings.githubToken) {
      toast.error("Save a GitHub token first.");
      return;
    }
    setStatus("deploying");
    setError(null);
    try {
      const r = await deploy({
        data: {
          token: settings.githubToken,
          mode,
          repo: repoName,
          description: project.initialTitle || `Generated by HYCS`,
          files: buildFiles(project),
          commitMessage,
          isPrivate,
        },
      });
      if (r.ok) {
        setResult({ repoUrl: r.repoUrl, pagesHint: r.pagesHint, commitSha: r.commitSha });
        setStatus("success");
        toast.success("Deployed to GitHub.");
      } else {
        setError(r.message);
        setStatus("failed");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Deployment failed.");
      setStatus("failed");
    }
  }

  return (
    <div className="fixed inset-0 z-[10001] bg-black/70 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-card border rounded-2xl w-full max-w-md p-5 max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2"><Github className="w-4 h-4" /><h3 className="font-bold">Deploy to GitHub</h3></div>
          <button onClick={onClose} className="p-1 rounded hover:bg-accent"><X className="w-4 h-4" /></button>
        </div>

        {!hasToken ? (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground">
              HYCS pushes your generated files into a repo you own using a GitHub Personal Access Token. We never see the token.
            </p>
            <ol className="text-xs space-y-1 list-decimal pl-4 text-muted-foreground">
              <li>Create a token at <a href="https://github.com/settings/tokens/new?scopes=repo&description=HYCS%20deploy" target="_blank" rel="noreferrer" className="text-primary hover:underline">github.com/settings/tokens <ExternalLink className="w-3 h-3 inline" /></a> with <strong>repo</strong> scope.</li>
              <li>Paste it below and click Save.</li>
            </ol>
            <input
              type="password"
              value={tokenDraft}
              onChange={(e) => setTokenDraft(e.target.value)}
              placeholder="ghp_..."
              className="w-full bg-input border rounded-lg px-3 py-2 text-sm font-mono outline-none"
              autoComplete="off"
            />
            <button
              onClick={() => { update({ githubToken: tokenDraft }); toast.success("Token saved."); }}
              disabled={!tokenDraft}
              className="w-full brand-bg text-white py-2 rounded-lg text-sm font-medium disabled:opacity-40"
            >
              Save token
            </button>
            <Link to="/settings" className="text-xs text-muted-foreground hover:text-foreground inline-flex items-center gap-1">
              Or manage in Settings →
            </Link>
          </div>
        ) : status === "success" && result ? (
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-green-400"><Check className="w-4 h-4" /> Deployed successfully.</div>
            <a href={result.repoUrl} target="_blank" rel="noreferrer" className="block border rounded-lg px-3 py-2 text-sm hover:bg-accent">
              <div className="font-medium flex items-center gap-1">Repository <ExternalLink className="w-3 h-3" /></div>
              <div className="text-xs text-muted-foreground truncate">{result.repoUrl}</div>
            </a>
            {result.pagesHint && (
              <div className="border rounded-lg px-3 py-2 text-sm">
                <div className="font-medium">GitHub Pages</div>
                <div className="text-xs text-muted-foreground mb-1">Enable Pages in the repo settings to publish at:</div>
                <div className="text-xs font-mono break-all">{result.pagesHint}</div>
              </div>
            )}
            <button onClick={onClose} className="w-full border py-2 rounded-lg text-sm">Close</button>
          </div>
        ) : (
          <div className="space-y-3">
            <div className="flex items-center gap-1 text-xs">
              <button onClick={() => setMode("create")} className={`flex-1 px-3 py-1.5 rounded-lg border ${mode === "create" ? "brand-bg text-white border-transparent" : "bg-card hover:bg-accent"}`}>
                Create new repo
              </button>
              <button onClick={() => setMode("existing")} className={`flex-1 px-3 py-1.5 rounded-lg border ${mode === "existing" ? "brand-bg text-white border-transparent" : "bg-card hover:bg-accent"}`}>
                Existing repo
              </button>
            </div>

            <div>
              <label className="text-xs text-muted-foreground">{mode === "create" ? "New repo name" : "Existing repo (owner/name or just name)"}</label>
              <input
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                placeholder={mode === "create" ? "my-coffee-shop" : "username/my-repo"}
                className="w-full bg-input border rounded-lg px-3 py-2 text-sm font-mono outline-none"
              />
            </div>

            <div>
              <label className="text-xs text-muted-foreground">Commit message</label>
              <input
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                className="w-full bg-input border rounded-lg px-3 py-2 text-sm outline-none"
              />
            </div>

            {mode === "create" && (
              <label className="flex items-center gap-2 text-xs">
                <input type="checkbox" checked={isPrivate} onChange={(e) => setIsPrivate(e.target.checked)} />
                Make repository private
              </label>
            )}

            {error && (
              <div className="flex items-start gap-2 text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg p-2">
                <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" /> {error}
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={run}
                disabled={!repoName || !commitMessage || status === "deploying"}
                className="flex-1 flex items-center justify-center gap-1.5 brand-bg text-white py-2 rounded-lg text-sm font-medium disabled:opacity-40"
              >
                {status === "deploying" ? <Loader2 className="w-4 h-4 animate-spin" /> : <Github className="w-4 h-4" />}
                {status === "deploying" ? "Deploying..." : "Deploy"}
              </button>
              <button onClick={downloadZip} className="text-xs px-3 py-2 rounded-lg border hover:bg-accent">
                Download zip
              </button>
            </div>
            <p className="text-[11px] text-muted-foreground">
              HYCS will not commit your API keys, settings, or BYOK data.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
